# general
seed: 42
workers: 0
dataset_dir: "./datasets"

# train options
batch_size: 1024
image_size: 128
start_epoch: 0
epochs: 200
dataset: "wsi" 
df_list: '../data/BCSS_128/BCSS_128.csv'

# model options
resnet: "ResNet18" 
feature_dim: 128
model_path: "./output/Simclr_res18_bcss128/"
reload: False

# loss options
learning_rate: 0.0003
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
